use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    sync::Arc,
};

use base64::{engine::general_purpose::STANDARD, Engine as _};
use jute::backend::notebook::{Cell, CellDagMetadata, NotebookRoot};
use serde::{Deserialize, Serialize, Serializer};
use serde_json::{json, Value};
use tracing::warn;

use crate::{
    dag::{
        engine::{ReactiveEngineClient, SourcePayload, SourcePush},
        graph::{
            resolve_source_cell_for_port, resolve_source_for_port, resolve_widget_emit_cell,
            SourcePortError, WidgetEmitError,
        },
        notebook_port_root, notebook_run_context, NotebookDag, Origin, PortEventDraft,
        PortEventKind, PortStore,
    },
    mcp::bridge::{AgentBridge, TauriBridgeRequester},
    spur_app::{self, archive, SpurAppExportOptions, SpurAppManifest, SpurAppPreflight},
};

const ANYWIDGET_COMMAND_KIND: &str = "anywidget-command";
const ANYWIDGET_COMMAND_RESPONSE_KIND: &str = "anywidget-command-response";
const INTENT_SOURCE_PUSH: &str = "source.push";
const INTENT_MODEL_STATE_UPDATE: &str = "model-state.update";
const INTENT_MODEL_STATE_CUSTOM: &str = "model-state.custom";

/// Shared Tauri state slot for the notebook daemon control plane.
pub type NotebookDaemonControlSlot =
    Arc<tokio::sync::Mutex<Option<Arc<crate::mcp::NotebookDaemonControl>>>>;

/// A frontend-originated anywidget command intent.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AnyWidgetCommandIntent {
    /// Correlation ID generated by the AFM iframe runtime.
    pub id: String,
    /// Must be `anywidget-command`.
    pub kind: String,
    /// Allowlisted intent name.
    pub name: String,
    /// Widget model/comm ID that should receive kernel comm messages.
    #[serde(default)]
    pub comm_id: Option<String>,
    /// Intent-specific JSON payload.
    pub msg: Value,
    /// Binary buffers attached to the anywidget custom message.
    #[serde(default)]
    pub buffers: Vec<Vec<u8>>,
}

/// Response sent back to the anywidget command caller.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct AnyWidgetCommandResponse {
    /// Correlation ID from the request.
    pub id: String,
    /// Always `anywidget-command-response`.
    pub kind: String,
    /// Intent-specific response or validation error.
    pub response: Value,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PublishSpurAppResponse {
    pub path: String,
    pub manifest: SpurAppManifest,
    pub asset_count: usize,
    #[serde(serialize_with = "serialize_spur_app_preflight")]
    pub preflight: SpurAppPreflight,
}

fn serialize_spur_app_preflight<S>(
    preflight: &SpurAppPreflight,
    serializer: S,
) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    #[derive(Serialize)]
    struct SpurAppPreflightJson<'a> {
        missing_dependency_locks: &'a [String],
        warnings: &'a [String],
    }

    SpurAppPreflightJson {
        missing_dependency_locks: &preflight.missing_dependency_locks,
        warnings: &preflight.warnings,
    }
    .serialize(serializer)
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct SourcePushIntentMsg {
    port: String,
    #[serde(default)]
    payload: Option<Value>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ModelStateUpdateIntentMsg {
    state: Value,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ModelStateCustomIntentMsg {
    content: Value,
}

#[async_trait::async_trait]
trait ModelStateCommGateway: Sync {
    fn slot_for_comm(&self, state: &jute::state::State, comm_id: &str) -> Option<String>;

    async fn send_comm_msg(
        &self,
        state: &jute::state::State,
        slot_id: &str,
        comm_id: &str,
        data: Value,
        buffers: Vec<Vec<u8>>,
    ) -> Result<(), String>;
}

struct JuteModelStateCommGateway;

#[async_trait::async_trait]
impl ModelStateCommGateway for JuteModelStateCommGateway {
    fn slot_for_comm(&self, state: &jute::state::State, comm_id: &str) -> Option<String> {
        jute::state::slot_for_comm(state, comm_id)
    }

    async fn send_comm_msg(
        &self,
        state: &jute::state::State,
        slot_id: &str,
        comm_id: &str,
        data: Value,
        buffers: Vec<Vec<u8>>,
    ) -> Result<(), String> {
        jute::commands::send_comm_msg(state, slot_id, comm_id, data, buffers)
            .await
            .map_err(|error| error.to_string())
    }
}

#[derive(Debug)]
struct AnyWidgetIntentError {
    code: &'static str,
    message: String,
}

impl AnyWidgetIntentError {
    fn new(code: &'static str, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }
}

#[derive(Debug, Clone)]
pub(crate) enum SourcePushIntentOrigin {
    Agent { tool: &'static str },
    Widget { model_id: String },
    Capture,
}

#[derive(Debug, Clone)]
pub(crate) struct ExternalSourcePushIntent {
    pub origin: SourcePushIntentOrigin,
    pub port: String,
    pub payload: SourcePayload,
}

#[derive(Debug)]
pub(crate) struct SourcePushIntentError {
    pub(crate) code: &'static str,
    pub(crate) message: String,
    pub(crate) port: String,
    origin: Origin,
}

impl SourcePushIntentError {
    fn new(
        code: &'static str,
        message: impl Into<String>,
        port: impl Into<String>,
        origin: Origin,
    ) -> Self {
        Self {
            code,
            message: message.into(),
            port: port.into(),
            origin,
        }
    }
}

/// Observe one allowlisted anywidget command intent from the frontend.
#[tauri::command]
pub async fn anywidget_command(
    state: tauri::State<'_, Arc<jute::state::State>>,
    daemon_control: tauri::State<'_, NotebookDaemonControlSlot>,
    intent: AnyWidgetCommandIntent,
) -> Result<AnyWidgetCommandResponse, jute::Error> {
    let control = { daemon_control.lock().await.clone() };
    let engine = match control {
        Some(control) => control.reactive_engine_client().await,
        None => None,
    };
    Ok(handle_anywidget_command_intent(&state, engine, intent).await)
}

/// Push a captured HTML canvas recording into the reactive source port store.
#[tauri::command]
pub async fn push_capture_port(
    state: tauri::State<'_, Arc<jute::state::State>>,
    daemon_control: tauri::State<'_, NotebookDaemonControlSlot>,
    port: String,
    webm_base64: String,
    duration_sec: f64,
) -> Result<Value, jute::Error> {
    let control = { daemon_control.lock().await.clone() };
    let engine = match control {
        Some(control) => control.reactive_engine_client().await,
        None => None,
    };
    push_capture_port_for_state(&state, engine, port, webm_base64, duration_sec).await
}

async fn push_capture_port_for_state(
    state: &jute::state::State,
    engine: Option<ReactiveEngineClient>,
    port: String,
    webm_base64: String,
    duration_sec: f64,
) -> Result<Value, jute::Error> {
    if !duration_sec.is_finite() || duration_sec < 0.0 {
        return Err(jute::Error::NotebookDaemon(
            "push_capture_port duration_sec must be a finite non-negative number".to_owned(),
        ));
    }

    let webm = STANDARD.decode(webm_base64).map_err(|error| {
        jute::Error::NotebookDaemon(format!("push_capture_port invalid webm_base64: {error}"))
    })?;
    let engine = engine.ok_or_else(|| {
        jute::Error::NotebookDaemon("push_capture_port reactive engine is unavailable".to_owned())
    })?;
    let intent = ExternalSourcePushIntent {
        origin: SourcePushIntentOrigin::Capture,
        port: port.clone(),
        payload: SourcePayload::MediaBlob {
            bytes: webm,
            mime: "video/webm".to_owned(),
            duration_sec: Some(duration_sec),
        },
    };
    let (root, _) = state.get_notebook().snapshot();
    push_validated_source_intent(&root, &engine, intent)
        .await
        .map_err(source_push_error_for_capture)?;

    Ok(json!({
        "port": port,
        "accepted": true,
    }))
}

pub fn publish_spur_app_for_paths(
    notebook_path: PathBuf,
    output_path: PathBuf,
    name: Option<String>,
    include_port_snapshots: bool,
) -> Result<PublishSpurAppResponse, String> {
    let dependency_roots = notebook_path
        .parent()
        .map(Path::to_path_buf)
        .into_iter()
        .collect();

    let exported = spur_app::export_spur_app(SpurAppExportOptions {
        notebook_path,
        output_path,
        name,
        widget_assets: Vec::new(),
        include_port_snapshots,
        dependency_roots,
    })
    .map_err(|error| error.to_string())?;

    let manifest_file = fs::File::open(&exported.output_path).map_err(|error| error.to_string())?;
    let manifest = archive::read_manifest(manifest_file).map_err(|error| error.to_string())?;

    Ok(PublishSpurAppResponse {
        path: exported.output_path.to_string_lossy().to_string(),
        manifest,
        asset_count: exported.asset_count,
        preflight: exported.preflight,
    })
}

#[tauri::command]
pub async fn publish_spur_app(
    notebook_path: String,
    output_path: String,
    name: Option<String>,
    include_port_snapshots: Option<bool>,
) -> Result<PublishSpurAppResponse, String> {
    publish_spur_app_for_paths(
        PathBuf::from(notebook_path),
        PathBuf::from(output_path),
        name,
        include_port_snapshots.unwrap_or(false),
    )
}

/// Core handler for an anywidget command intent, defaulting to the real
/// [`JuteModelStateCommGateway`]. Public so integration tests can drive the
/// real gateway path without a Tauri `State` wrapper.
pub async fn handle_anywidget_command_intent(
    state: &jute::state::State,
    engine: Option<ReactiveEngineClient>,
    intent: AnyWidgetCommandIntent,
) -> AnyWidgetCommandResponse {
    handle_anywidget_command_intent_with_gateway(state, engine, intent, &JuteModelStateCommGateway)
        .await
}

async fn handle_anywidget_command_intent_with_gateway(
    state: &jute::state::State,
    engine: Option<ReactiveEngineClient>,
    intent: AnyWidgetCommandIntent,
    gateway: &dyn ModelStateCommGateway,
) -> AnyWidgetCommandResponse {
    let response = if intent.kind != ANYWIDGET_COMMAND_KIND {
        Err(audit_rejected_intent(
            &intent,
            "invalid_intent_kind",
            format!("unsupported anywidget command kind: {}", intent.kind),
        ))
    } else {
        match intent.name.as_str() {
            INTENT_SOURCE_PUSH => handle_source_push_intent(state, engine, &intent).await,
            INTENT_MODEL_STATE_UPDATE => {
                handle_model_state_update_intent_with_gateway(state, &intent, gateway).await
            }
            INTENT_MODEL_STATE_CUSTOM => {
                handle_model_state_custom_intent_with_gateway(state, &intent, gateway).await
            }
            _ => Err(audit_rejected_intent(
                &intent,
                "intent_not_allowlisted",
                format!("anywidget intent is not allowlisted: {}", intent.name),
            )),
        }
    };

    match response {
        Ok(response) => anywidget_response(intent.id, response),
        Err(error) => anywidget_error_response(intent.id, error),
    }
}

async fn handle_source_push_intent(
    state: &jute::state::State,
    engine: Option<ReactiveEngineClient>,
    intent: &AnyWidgetCommandIntent,
) -> Result<Value, AnyWidgetIntentError> {
    let msg: SourcePushIntentMsg = serde_json::from_value(intent.msg.clone()).map_err(|error| {
        audit_rejected_intent(
            intent,
            "invalid_source_push_intent",
            format!("source.push requires {{ port, payload? }}: {error}"),
        )
    })?;
    let ipc_bytes = source_push_ipc_bytes(msg.payload, &intent.buffers)?;
    let engine = engine.ok_or_else(|| {
        AnyWidgetIntentError::new(
            "reactive_engine_unavailable",
            "source.push requires the reactive engine",
        )
    })?;
    let (root, _) = state.get_notebook().snapshot();
    let model_id = intent
        .comm_id
        .as_deref()
        .map(str::trim)
        .filter(|comm_id| !comm_id.is_empty())
        .ok_or_else(|| {
            audit_rejected_intent(
                intent,
                "missing_model_id",
                "source.push requires commId for widget authorization",
            )
        })?
        .to_owned();
    push_validated_source_intent(
        &root,
        &engine,
        ExternalSourcePushIntent {
            origin: SourcePushIntentOrigin::Widget { model_id },
            port: msg.port.clone(),
            payload: SourcePayload::IpcBytes(ipc_bytes),
        },
    )
    .await
    .map_err(source_push_error_for_widget)?;

    Ok(json!({
        "accepted": true,
        "port": msg.port,
    }))
}

/// Handles `model-state.update` by echoing and best-effort queueing a `comm_msg`.
async fn handle_model_state_update_intent_with_gateway(
    state: &jute::state::State,
    intent: &AnyWidgetCommandIntent,
    gateway: &dyn ModelStateCommGateway,
) -> Result<Value, AnyWidgetIntentError> {
    let msg: ModelStateUpdateIntentMsg =
        serde_json::from_value(intent.msg.clone()).map_err(|error| {
            audit_rejected_intent(
                intent,
                "invalid_model_state_intent",
                format!("model-state.update requires {{ state }}: {error}"),
            )
        })?;
    if !msg.state.is_object() {
        return Err(audit_rejected_intent(
            intent,
            "invalid_model_state",
            "model-state.update state must be a JSON object",
        ));
    }

    let model_state = msg.state;
    let kernel_delivery = model_state_kernel_delivery(
        state,
        intent,
        json!({
            "method": "update",
            "state": model_state.clone(),
        }),
        gateway,
        "model-state.update",
    )
    .await;

    Ok(json!({
        "method": "update",
        "state": model_state,
        "kernelDelivery": kernel_delivery,
    }))
}

async fn handle_model_state_custom_intent_with_gateway(
    state: &jute::state::State,
    intent: &AnyWidgetCommandIntent,
    gateway: &dyn ModelStateCommGateway,
) -> Result<Value, AnyWidgetIntentError> {
    let msg: ModelStateCustomIntentMsg =
        serde_json::from_value(intent.msg.clone()).map_err(|error| {
            audit_rejected_intent(
                intent,
                "invalid_model_state_custom_intent",
                format!("model-state.custom requires {{ content }}: {error}"),
            )
        })?;

    let content = msg.content;
    let kernel_delivery = model_state_kernel_delivery(
        state,
        intent,
        json!({
            "method": "custom",
            "content": content.clone(),
        }),
        gateway,
        "model-state.custom",
    )
    .await;

    Ok(json!({
        "method": "custom",
        "content": content,
        "kernelDelivery": kernel_delivery,
    }))
}

async fn model_state_kernel_delivery(
    state: &jute::state::State,
    intent: &AnyWidgetCommandIntent,
    data: Value,
    gateway: &dyn ModelStateCommGateway,
    intent_name: &'static str,
) -> Value {
    let Some(comm_id) = intent
        .comm_id
        .as_deref()
        .map(str::trim)
        .filter(|comm_id| !comm_id.is_empty())
    else {
        return json!({
            "status": "skipped",
            "reason": "missing_comm_id",
        });
    };

    let Some(slot_id) = gateway.slot_for_comm(state, comm_id) else {
        return json!({
            "status": "skipped",
            "commId": comm_id,
            "reason": "comm_not_open",
        });
    };

    match gateway
        .send_comm_msg(state, &slot_id, comm_id, data, intent.buffers.clone())
        .await
    {
        Ok(()) => json!({
            "status": "sent",
            "commId": comm_id,
            "slotId": slot_id,
        }),
        Err(error) => {
            warn!(
                command_id = %intent.id,
                intent_name,
                comm_id,
                slot_id,
                %error,
                "failed to send anywidget comm_msg"
            );
            json!({
                "status": "failed",
                "commId": comm_id,
                "slotId": slot_id,
                "error": error,
            })
        }
    }
}

fn source_push_ipc_bytes(
    payload: Option<Value>,
    buffers: &[Vec<u8>],
) -> Result<Vec<u8>, AnyWidgetIntentError> {
    match (payload, buffers) {
        (Some(_), [_first, ..]) => Err(AnyWidgetIntentError::new(
            "ambiguous_source_payload",
            "source.push accepts either msg.payload or one binary buffer, not both",
        )),
        (Some(payload), []) => serde_json::from_value::<Vec<u8>>(payload).map_err(|error| {
            AnyWidgetIntentError::new(
                "invalid_source_payload",
                format!("source.push payload must be an array of bytes: {error}"),
            )
        }),
        (None, [buffer]) => Ok(buffer.clone()),
        (None, []) => Err(AnyWidgetIntentError::new(
            "missing_source_payload",
            "source.push requires msg.payload or one binary buffer",
        )),
        (None, buffers) => Err(AnyWidgetIntentError::new(
            "ambiguous_source_payload",
            format!(
                "source.push accepts one binary buffer, got {}",
                buffers.len()
            ),
        )),
    }
}

fn audit_rejected_intent(
    intent: &AnyWidgetCommandIntent,
    code: &'static str,
    message: impl Into<String>,
) -> AnyWidgetIntentError {
    let message = message.into();
    warn!(
        command_id = %intent.id,
        intent_name = %intent.name,
        code,
        "rejected anywidget command intent"
    );
    AnyWidgetIntentError::new(code, message)
}

pub(crate) async fn push_validated_source_intent(
    root: &NotebookRoot,
    engine: &ReactiveEngineClient,
    intent: ExternalSourcePushIntent,
) -> Result<(), SourcePushIntentError> {
    match validate_source_push_intent(root, intent) {
        Ok(push) => engine.push_source(push).await.map_err(|error| {
            SourcePushIntentError::new(
                "source_push_failed",
                format!("failed to queue source push: {error}"),
                "",
                Origin::Agent {
                    tool: "source_push".to_owned(),
                },
            )
        }),
        Err(error) => {
            emit_intent_rejected(engine, &error).await;
            Err(error)
        }
    }
}

fn validate_source_push_intent(
    root: &NotebookRoot,
    intent: ExternalSourcePushIntent,
) -> Result<SourcePush, SourcePushIntentError> {
    let port = intent.port;
    if port.is_empty() {
        return Err(SourcePushIntentError::new(
            "invalid_source_port",
            "source push port must not be empty",
            port,
            rejection_origin(&intent.origin),
        ));
    }
    let origin = source_push_origin(root, &intent.origin, &port)?;

    let source = match &intent.origin {
        SourcePushIntentOrigin::Capture => {
            let (_cell_id, source) = resolve_source_cell_for_port(root, &port)
                .map_err(|error| source_port_error("source push", error, origin.clone()))?;
            if source.kind != "canvas-capture" {
                return Err(SourcePushIntentError::new(
                    "invalid_source_kind",
                    format!(
                        "push_capture_port source kind must be canvas-capture for port: {port}"
                    ),
                    port,
                    origin,
                ));
            }
            source
        }
        SourcePushIntentOrigin::Agent { .. } | SourcePushIntentOrigin::Widget { .. } => {
            resolve_source_for_port(root, &port)
                .map_err(|error| source_port_error("source.push", error, origin.clone()))?
        }
    };

    match (&intent.origin, &intent.payload) {
        (
            SourcePushIntentOrigin::Agent { .. } | SourcePushIntentOrigin::Widget { .. },
            SourcePayload::IpcBytes(_),
        )
        | (SourcePushIntentOrigin::Capture, SourcePayload::MediaBlob { .. }) => {}
        (SourcePushIntentOrigin::Capture, SourcePayload::IpcBytes(_)) => {
            return Err(SourcePushIntentError::new(
                "invalid_source_payload_class",
                "push_capture_port requires a media blob payload",
                port,
                origin,
            ));
        }
        (
            SourcePushIntentOrigin::Agent { .. } | SourcePushIntentOrigin::Widget { .. },
            SourcePayload::MediaBlob { .. },
        ) => {
            return Err(SourcePushIntentError::new(
                "invalid_source_payload_class",
                "source.push accepts dataframe IPC payloads only",
                port,
                origin,
            ));
        }
    }

    Ok(SourcePush {
        source,
        payload: intent.payload,
    })
}

fn rejection_origin(origin: &SourcePushIntentOrigin) -> Origin {
    match origin {
        SourcePushIntentOrigin::Agent { tool } => Origin::Agent {
            tool: (*tool).to_owned(),
        },
        SourcePushIntentOrigin::Widget { model_id } => Origin::Widget {
            model_id: model_id.clone(),
            cell_id: String::new(),
        },
        SourcePushIntentOrigin::Capture => Origin::Capture {
            cell_id: String::new(),
        },
    }
}

fn source_push_origin(
    root: &NotebookRoot,
    origin: &SourcePushIntentOrigin,
    port: &str,
) -> Result<Origin, SourcePushIntentError> {
    match origin {
        SourcePushIntentOrigin::Agent { tool } => Ok(Origin::Agent {
            tool: (*tool).to_owned(),
        }),
        SourcePushIntentOrigin::Widget { model_id } => {
            let cell_id = resolve_widget_emit_cell(root, model_id, port)
                .map_err(|error| widget_emit_error(error, port))?;
            Ok(Origin::Widget {
                model_id: model_id.clone(),
                cell_id,
            })
        }
        SourcePushIntentOrigin::Capture => {
            let (cell_id, _source) = resolve_source_cell_for_port(root, port).map_err(|error| {
                source_port_error(
                    "push_capture_port",
                    error,
                    Origin::Capture {
                        cell_id: String::new(),
                    },
                )
            })?;
            Ok(Origin::Capture { cell_id })
        }
    }
}

fn source_port_error(
    prefix: &'static str,
    error: SourcePortError,
    origin: Origin,
) -> SourcePushIntentError {
    match error {
        SourcePortError::NotDeclared { port } => SourcePushIntentError::new(
            "source_port_not_declared",
            format!("{prefix} port is not declared: {port}"),
            port,
            origin,
        ),
        SourcePortError::Ambiguous { port } => SourcePushIntentError::new(
            "ambiguous_source_port",
            format!("{prefix} port is ambiguous: {port}"),
            port,
            origin,
        ),
    }
}

fn widget_emit_error(error: WidgetEmitError, requested_port: &str) -> SourcePushIntentError {
    match error {
        WidgetEmitError::ModelNotFound { model_id } => SourcePushIntentError::new(
            "widget_model_not_found",
            format!("source.push widget model is not associated with a frontend cell: {model_id}"),
            requested_port,
            Origin::Widget {
                model_id,
                cell_id: String::new(),
            },
        ),
        WidgetEmitError::CellMissingFrontendMetadata { model_id, cell_id } => {
            SourcePushIntentError::new(
                "frontend_metadata_missing",
                format!("source.push frontend cell has no emits metadata: {cell_id}"),
                requested_port,
                Origin::Widget { model_id, cell_id },
            )
        }
        WidgetEmitError::EmitNotDeclared {
            model_id,
            cell_id,
            port,
        } => SourcePushIntentError::new(
            "source_emit_not_declared",
            format!("source.push port is not declared in frontend emits: {port}"),
            port,
            Origin::Widget { model_id, cell_id },
        ),
    }
}

async fn emit_intent_rejected(engine: &ReactiveEngineClient, error: &SourcePushIntentError) {
    if let Err(emit_error) = engine
        .emit_port_event(PortEventDraft::new(PortEventKind::IntentRejected {
            origin: error.origin.clone(),
            code: error.code.to_owned(),
            port: error.port.clone(),
        }))
        .await
    {
        warn!(%emit_error, code = error.code, "failed to emit rejected source intent");
    }
}

fn source_push_error_for_widget(error: SourcePushIntentError) -> AnyWidgetIntentError {
    AnyWidgetIntentError::new(error.code, error.message)
}

fn source_push_error_for_capture(error: SourcePushIntentError) -> jute::Error {
    jute::Error::NotebookDaemon(error.message)
}

fn anywidget_response(id: String, response: Value) -> AnyWidgetCommandResponse {
    AnyWidgetCommandResponse {
        id,
        kind: ANYWIDGET_COMMAND_RESPONSE_KIND.to_owned(),
        response,
    }
}

fn anywidget_error_response(id: String, error: AnyWidgetIntentError) -> AnyWidgetCommandResponse {
    anywidget_response(
        id,
        json!({
            "error": {
                "code": error.code,
                "message": error.message,
            }
        }),
    )
}

/// Return the active notebook DAG snapshot for the Tauri frontend.
#[tauri::command]
pub async fn notebook_dag_status(
    state: tauri::State<'_, std::sync::Arc<jute::state::State>>,
) -> Result<Value, jute::Error> {
    notebook_dag_status_for_state(&state)
}

/// Run a notebook cell through the reactive DAG engine and cascade downstream cells.
#[tauri::command]
pub async fn notebook_run_cascade(
    state: tauri::State<'_, Arc<jute::state::State>>,
    bridge: tauri::State<'_, Arc<AgentBridge>>,
    app: tauri::AppHandle,
    cell_id: String,
) -> Result<Value, jute::Error> {
    let notebook = state.get_notebook();
    let path = notebook.path().ok_or_else(|| {
        jute::Error::NotebookDaemon("notebook_run_cascade requires an open notebook".to_string())
    })?;
    let mut context = notebook_run_context(
        &path,
        Arc::clone(state.inner()),
        Arc::new(TauriBridgeRequester::without_app(Arc::clone(
            bridge.inner(),
        ))),
        Some(app),
        None,
    );
    let report = context
        .engine
        .run_cell_and_cascade(&cell_id)
        .await
        .map_err(|error| {
            jute::Error::NotebookDaemon(format!("notebook_run_cascade failed: {error}"))
        })?;

    Ok(json!({
        "cell_id": cell_id,
        "runs": report.runs.into_iter().map(|run| {
            json!({
                "cell_id": run.cell_id,
                "status": run.status.as_str(),
            })
        }).collect::<Vec<_>>(),
    }))
}

/// Run a notebook cell through the reactive DAG engine without cascading downstream cells.
#[tauri::command]
pub async fn notebook_run_cell(
    state: tauri::State<'_, Arc<jute::state::State>>,
    bridge: tauri::State<'_, Arc<AgentBridge>>,
    app: tauri::AppHandle,
    cell_id: String,
) -> Result<Value, jute::Error> {
    let notebook = state.get_notebook();
    let path = notebook.path().ok_or_else(|| {
        jute::Error::NotebookDaemon("notebook_run_cell requires an open notebook".to_string())
    })?;
    let mut context = notebook_run_context(
        &path,
        Arc::clone(state.inner()),
        Arc::new(TauriBridgeRequester::without_app(Arc::clone(
            bridge.inner(),
        ))),
        Some(app),
        None,
    );
    let report = context.engine.run_cell(&cell_id).await.map_err(|error| {
        jute::Error::NotebookDaemon(format!("notebook_run_cell failed: {error}"))
    })?;

    Ok(json!({
        "cell_id": report.cell_id,
        "status": report.status.as_str(),
    }))
}

fn notebook_dag_status_for_state(state: &jute::state::State) -> Result<Value, jute::Error> {
    let notebook = state.get_notebook();
    let path = notebook.path().ok_or_else(|| {
        jute::Error::NotebookDaemon("notebook_dag_status requires an open notebook".to_string())
    })?;
    let (root, version) = notebook.snapshot();
    notebook_dag_status_snapshot(&root, version, &path)
}

fn notebook_dag_status_snapshot(
    root: &NotebookRoot,
    version: u64,
    path: &Path,
) -> Result<Value, jute::Error> {
    let dag = build_graph(root)?;
    let port_manifest = PortStore::open_read_only_at(notebook_port_root(path))
        .map_err(|error| {
            jute::Error::NotebookDaemon(format!(
                "notebook_dag_status failed to read port manifest: {error}"
            ))
        })?
        .manifest()
        .iter()
        .map(|(port, entry)| (port.clone(), entry.version))
        .collect::<BTreeMap<_, _>>();

    Ok(json!({
        "notebook_version": version,
        "nodes": dag_nodes(root),
        "edges": dag.edges(),
        "port_manifest": port_manifest,
    }))
}

fn build_graph(root: &NotebookRoot) -> Result<NotebookDag, jute::Error> {
    NotebookDag::from_metadata(root.cells.iter().filter_map(|cell| {
        let id = cell_id(cell)?;
        let dag = cell_dag(cell)?;
        Some((id, dag.clone()))
    }))
    .map_err(|error| {
        jute::Error::NotebookDaemon(format!("notebook_dag_status failed to build DAG: {error}"))
    })
}

fn dag_nodes(root: &NotebookRoot) -> Vec<Value> {
    root.cells
        .iter()
        .filter_map(|cell| {
            let id = cell_id(cell)?;
            let dag = cell_dag(cell)?;
            Some(json!({
                "id": id,
                "state": {
                    "kind": cell_kind(cell),
                    "version": cell_version(cell),
                    "execution_count": cell_execution_count(cell),
                },
                "dag": dag,
            }))
        })
        .collect()
}

fn cell_id(cell: &Cell) -> Option<String> {
    match cell {
        Cell::Raw(cell) => cell.id.clone(),
        Cell::Markdown(cell) => cell.id.clone(),
        Cell::Code(cell) => cell.id.clone(),
    }
}

fn cell_kind(cell: &Cell) -> &'static str {
    match cell {
        Cell::Raw(_) => "raw",
        Cell::Markdown(_) => "markdown",
        Cell::Code(_) => "code",
    }
}

fn cell_dag(cell: &Cell) -> Option<&CellDagMetadata> {
    match cell {
        Cell::Raw(cell) => cell.metadata.spur.as_ref()?.dag.as_ref(),
        Cell::Markdown(cell) => cell.metadata.spur.as_ref()?.dag.as_ref(),
        Cell::Code(cell) => cell.metadata.spur.as_ref()?.dag.as_ref(),
    }
}

fn cell_version(cell: &Cell) -> Option<u64> {
    match cell {
        Cell::Raw(cell) => cell.metadata.spur.as_ref().map(|spur| spur.version),
        Cell::Markdown(cell) => cell.metadata.spur.as_ref().map(|spur| spur.version),
        Cell::Code(cell) => cell.metadata.spur.as_ref().map(|spur| spur.version),
    }
}

fn cell_execution_count(cell: &Cell) -> Option<u32> {
    match cell {
        Cell::Code(cell) => cell.execution_count,
        Cell::Raw(_) | Cell::Markdown(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use std::{
        collections::BTreeMap,
        future::Future,
        pin::Pin,
        sync::{Arc, Mutex},
        time::Duration,
    };

    use arrow_array::{Int64Array, RecordBatch};
    use arrow_schema::{DataType, Field, Schema};
    use base64::Engine as _;
    use jute::backend::notebook::{
        Cell, CellDagMetadata, CellMetadata, CodeCell, DagSource, FrontendCellMetadata,
        MultilineString, NotebookMetadata, NotebookRoot, Output, OutputDisplayData, PortSpec,
        SpurCellMetadata,
    };
    use tempfile::TempDir;

    use crate::{
        dag::{
            engine::{
                CellRunOutcome, CellRunRequest, CellRunStatus, CellRunner, EngineError,
                KernelEnsureRequest, ReactiveEngineClient, SourcePush,
            },
            notebook_run_context_with_runner, Origin, PortEventKind, PortEventSequencer,
            PortEventSequencerConfig,
        },
        mcp::bridge::{BridgeError, BridgeRequestFuture, BridgeRequester},
    };
    use tokio::sync::mpsc;

    use super::*;

    #[derive(Default)]
    struct TestBridge;

    impl BridgeRequester for TestBridge {
        fn listener_registered(&self) -> bool {
            true
        }

        fn window_alive(&self) -> bool {
            true
        }

        fn notebook_open(&self) -> bool {
            true
        }

        fn request<'a>(
            &'a self,
            _method: &'static str,
            _params: Value,
            _timeout: Duration,
        ) -> BridgeRequestFuture<'a> {
            Box::pin(async { Err(BridgeError::NotebookNotOpen) })
        }
    }

    #[derive(Clone)]
    struct RecordingRunner {
        requests: Arc<Mutex<Vec<CellRunRequest>>>,
    }

    impl CellRunner for RecordingRunner {
        fn run_cell<'a>(
            &'a self,
            request: CellRunRequest,
        ) -> Pin<Box<dyn Future<Output = Result<CellRunOutcome, EngineError>> + Send + 'a>>
        {
            Box::pin(async move {
                self.requests.lock().expect("requests").push(request);
                Ok(CellRunOutcome {
                    status: CellRunStatus::Succeeded,
                })
            })
        }

        fn ensure_kernel<'a>(
            &'a self,
            _request: KernelEnsureRequest,
        ) -> Pin<Box<dyn Future<Output = Result<(), EngineError>> + Send + 'a>> {
            Box::pin(async { Ok(()) })
        }
    }

    fn notebook(cells: Vec<Cell>) -> NotebookRoot {
        NotebookRoot {
            metadata: NotebookMetadata {
                kernelspec: None,
                language_info: None,
                orig_nbformat: None,
                title: None,
                authors: None,
                jute_deck: None,
                other: Default::default(),
            },
            nbformat_minor: 5,
            nbformat: 4,
            cells,
        }
    }

    fn cell(
        id: &str,
        produces: Vec<&str>,
        consumes: Vec<&str>,
        execution_count: Option<u32>,
    ) -> Cell {
        Cell::Code(CodeCell {
            id: Some(id.to_owned()),
            metadata: CellMetadata {
                spur: Some(SpurCellMetadata {
                    version: 7,
                    last_edited_by: Some("brain".to_owned()),
                    datasource_setup: None,
                    dag: Some(CellDagMetadata {
                        produces: produces
                            .into_iter()
                            .map(|port| PortSpec {
                                port: port.to_string(),
                                repr: "arrow".to_string(),
                                display: None,
                                class: None,
                                schema: None,
                            })
                            .collect(),
                        consumes: consumes.into_iter().map(str::to_string).collect(),
                        source: None,
                    }),
                    code_type: None,
                    frontend: None,
                }),
                jute_deck: None,
                other: Default::default(),
            },
            source: MultilineString::Single("print('ok')".to_string()),
            execution_count,
            outputs: Vec::new(),
        })
    }

    fn source_cell(id: &str, source: DagSource) -> Cell {
        Cell::Code(CodeCell {
            id: Some(id.to_owned()),
            metadata: CellMetadata {
                spur: Some(SpurCellMetadata {
                    version: 7,
                    last_edited_by: Some("brain".to_owned()),
                    datasource_setup: None,
                    dag: Some(CellDagMetadata {
                        produces: Vec::new(),
                        consumes: Vec::new(),
                        source: Some(source),
                    }),
                    code_type: None,
                    frontend: None,
                }),
                jute_deck: None,
                other: Default::default(),
            },
            source: MultilineString::Single("print('source')".to_owned()),
            execution_count: None,
            outputs: Vec::new(),
        })
    }

    fn frontend_source_cell(id: &str, model_id: &str, emits: Vec<&str>, source: DagSource) -> Cell {
        Cell::Code(CodeCell {
            id: Some(id.to_owned()),
            metadata: CellMetadata {
                spur: Some(SpurCellMetadata {
                    version: 7,
                    last_edited_by: Some("brain".to_owned()),
                    datasource_setup: None,
                    dag: Some(CellDagMetadata {
                        produces: Vec::new(),
                        consumes: Vec::new(),
                        source: Some(source),
                    }),
                    code_type: None,
                    frontend: Some(FrontendCellMetadata {
                        kind: Some("html".to_owned()),
                        binds: Vec::new(),
                        emits: emits.into_iter().map(str::to_owned).collect(),
                    }),
                }),
                jute_deck: None,
                other: Default::default(),
            },
            source: MultilineString::Single("<div></div>".to_owned()),
            execution_count: Some(1),
            outputs: vec![Output::DisplayData(OutputDisplayData {
                data: BTreeMap::from([(
                    "application/vnd.jupyter.widget-view+json".to_owned(),
                    json!({ "model_id": model_id }),
                )]),
                metadata: BTreeMap::new(),
                other: Default::default(),
            })],
        })
    }

    fn source_engine_for_test() -> (ReactiveEngineClient, mpsc::Receiver<SourcePush>) {
        let (tx, rx) = mpsc::channel(4);
        (ReactiveEngineClient::new_for_test(tx), rx)
    }

    fn source_engine_with_events_for_test() -> (
        ReactiveEngineClient,
        mpsc::Receiver<SourcePush>,
        PortEventSequencer,
    ) {
        let (tx, rx) = mpsc::channel(4);
        let sequencer = PortEventSequencer::spawn(PortEventSequencerConfig::default());
        (
            ReactiveEngineClient::new_with_port_events(tx, sequencer.client()),
            rx,
            sequencer,
        )
    }

    fn ipc_batch() -> RecordBatch {
        let schema = Arc::new(Schema::new(vec![Field::new(
            "value",
            DataType::Int64,
            false,
        )]));
        RecordBatch::try_new(schema, vec![Arc::new(Int64Array::from(vec![1]))]).expect("batch")
    }

    #[test]
    fn command_snapshot_matches_mcp_payload_shape() {
        let temp = TempDir::new().expect("temp dir");
        let notebook_path = temp.path().join("nb.ipynb");
        let state = jute::state::State::new();
        state.get_notebook().load(
            &notebook_path,
            notebook(vec![
                cell("producer", vec!["raw"], vec![], Some(1)),
                cell("consumer", vec![], vec!["raw"], None),
            ]),
        );
        let port_root = notebook_port_root(&notebook_path);
        PortStore::open_at(&port_root)
            .expect("port store")
            .put("raw", &ipc_batch())
            .expect("put port");

        let snapshot = notebook_dag_status_for_state(&state).expect("status snapshot");

        assert_eq!(snapshot["notebook_version"], 1);
        assert_eq!(snapshot["nodes"][0]["state"]["kind"], "code");
        assert_eq!(snapshot["nodes"][0]["state"]["execution_count"], 1);
        assert_eq!(
            snapshot["nodes"][1]["state"]["execution_count"],
            Value::Null
        );
        assert_eq!(
            snapshot["edges"][0],
            json!({ "producer": "producer", "consumer": "consumer", "port": "raw" })
        );
        assert_eq!(snapshot["port_manifest"]["raw"], 1);
    }

    #[tokio::test]
    async fn command_run_context_resolves_kernel_with_daemon_none_and_dispatches() {
        let temp = TempDir::new().expect("temp dir");
        let notebook_path = temp.path().join("nb.ipynb");
        let state = Arc::new(jute::state::State::new());
        state.get_notebook().load(
            &notebook_path,
            notebook(vec![cell("producer", vec!["raw"], vec![], None)]),
        );
        let requests = Arc::new(Mutex::new(Vec::new()));

        let mut context = notebook_run_context_with_runner(
            &notebook_path,
            Arc::clone(&state),
            Arc::new(TestBridge),
            None,
            None,
            {
                let requests = Arc::clone(&requests);
                move |_deps| RecordingRunner { requests }
            },
        );

        assert!(context.deps.daemon.is_none());
        context.engine.run_cell("producer").await.expect("run cell");

        let requests = requests.lock().expect("requests");
        assert_eq!(requests.len(), 1);
        assert_eq!(requests[0].cell_id, "producer");
        assert_eq!(
            requests[0].notebook_path,
            notebook_path.to_string_lossy().as_ref()
        );
        assert_eq!(
            requests[0].kernel_id,
            Some(format!(
                "{}#python3",
                jute::state::notebook_slot_id(notebook_path.to_string_lossy().as_ref())
            ))
        );
    }

    #[tokio::test]
    async fn anywidget_source_push_intent_queues_declared_source_port() {
        let temp = TempDir::new().expect("temp dir");
        let notebook_path = temp.path().join("nb.ipynb");
        let state = jute::state::State::new();
        let source = DagSource {
            kind: "frontend".to_owned(),
            port: "horizon".to_owned(),
            class: None,
            schema: None,
        };
        state.get_notebook().load(
            &notebook_path,
            notebook(vec![frontend_source_cell(
                "slider",
                "model-1",
                vec!["horizon"],
                source.clone(),
            )]),
        );
        let (engine, mut source_rx) = source_engine_for_test();

        let response = handle_anywidget_command_intent(
            &state,
            Some(engine),
            AnyWidgetCommandIntent {
                id: "cmd-1".to_owned(),
                kind: "anywidget-command".to_owned(),
                name: "source.push".to_owned(),
                comm_id: Some("model-1".to_owned()),
                msg: json!({ "port": "horizon", "payload": [1, 2, 3] }),
                buffers: Vec::new(),
            },
        )
        .await;

        assert_eq!(response.kind, "anywidget-command-response");
        assert_eq!(response.id, "cmd-1");
        assert_eq!(response.response["accepted"], true);
        assert_eq!(response.response["port"], "horizon");
        let push = source_rx.recv().await.expect("source push queued");
        assert_eq!(push.source, source);
        assert_eq!(push.payload, SourcePayload::IpcBytes(vec![1, 2, 3]));
    }

    #[tokio::test]
    async fn anywidget_source_push_rejects_undeclared_emit_and_emits_event() {
        let temp = TempDir::new().expect("temp dir");
        let notebook_path = temp.path().join("nb.ipynb");
        let state = jute::state::State::new();
        state.get_notebook().load(
            &notebook_path,
            notebook(vec![frontend_source_cell(
                "slider",
                "model-1",
                vec!["allowed"],
                DagSource {
                    kind: "frontend".to_owned(),
                    port: "blocked".to_owned(),
                    class: None,
                    schema: None,
                },
            )]),
        );
        let (engine, mut source_rx, sequencer) = source_engine_with_events_for_test();
        let mut events_rx = engine
            .subscribe_port_events()
            .expect("port event subscription");

        let response = handle_anywidget_command_intent(
            &state,
            Some(engine.clone()),
            AnyWidgetCommandIntent {
                id: "cmd-denied".to_owned(),
                kind: "anywidget-command".to_owned(),
                name: "source.push".to_owned(),
                comm_id: Some("model-1".to_owned()),
                msg: json!({ "port": "blocked", "payload": [1, 2, 3] }),
                buffers: Vec::new(),
            },
        )
        .await;

        assert_eq!(
            response.response["error"]["code"],
            "source_emit_not_declared"
        );
        assert!(source_rx.try_recv().is_err());
        let event = tokio::time::timeout(Duration::from_secs(1), events_rx.recv())
            .await
            .expect("intent rejection event")
            .expect("event broadcast");
        assert_eq!(
            event.kind(),
            &PortEventKind::IntentRejected {
                origin: Origin::Widget {
                    model_id: "model-1".to_owned(),
                    cell_id: "slider".to_owned(),
                },
                code: "source_emit_not_declared".to_owned(),
                port: "blocked".to_owned(),
            }
        );
        drop(engine);
        sequencer.shutdown().await;
    }

    #[tokio::test]
    async fn anywidget_source_push_accepts_declared_emit() {
        let temp = TempDir::new().expect("temp dir");
        let notebook_path = temp.path().join("nb.ipynb");
        let state = jute::state::State::new();
        let source = DagSource {
            kind: "frontend".to_owned(),
            port: "allowed".to_owned(),
            class: None,
            schema: None,
        };
        state.get_notebook().load(
            &notebook_path,
            notebook(vec![frontend_source_cell(
                "slider",
                "model-1",
                vec!["allowed"],
                source.clone(),
            )]),
        );
        let (engine, mut source_rx) = source_engine_for_test();

        let response = handle_anywidget_command_intent(
            &state,
            Some(engine),
            AnyWidgetCommandIntent {
                id: "cmd-allowed".to_owned(),
                kind: "anywidget-command".to_owned(),
                name: "source.push".to_owned(),
                comm_id: Some("model-1".to_owned()),
                msg: json!({ "port": "allowed", "payload": [9] }),
                buffers: Vec::new(),
            },
        )
        .await;

        assert_eq!(response.response["accepted"], true);
        let push = source_rx.recv().await.expect("source push queued");
        assert_eq!(push.source, source);
        assert_eq!(push.payload, SourcePayload::IpcBytes(vec![9]));
    }

    #[tokio::test]
    async fn push_capture_port_queues_canvas_capture_media_blob() {
        let temp = TempDir::new().expect("temp dir");
        let notebook_path = temp.path().join("nb.ipynb");
        let state = jute::state::State::new();
        state.get_notebook().load(
            &notebook_path,
            notebook(vec![source_cell(
                "capture",
                DagSource {
                    kind: "canvas-capture".to_owned(),
                    port: "capture".to_owned(),
                    class: None,
                    schema: None,
                },
            )]),
        );
        let (engine, mut source_rx) = source_engine_for_test();

        let response = push_capture_port_for_state(
            &state,
            Some(engine),
            "capture".to_owned(),
            base64::engine::general_purpose::STANDARD.encode(b"webm bytes"),
            1.5,
        )
        .await
        .expect("capture push succeeds");

        assert_eq!(response["port"], "capture");
        assert_eq!(response["accepted"], true);
        let push = source_rx.recv().await.expect("source push queued");
        assert_eq!(push.source.kind, "canvas-capture");
        assert_eq!(push.source.port, "capture");

        assert_eq!(
            push.payload,
            SourcePayload::MediaBlob {
                bytes: b"webm bytes".to_vec(),
                mime: "video/webm".to_owned(),
                duration_sec: Some(1.5),
            }
        );
    }

    #[tokio::test]
    async fn push_capture_port_rejects_non_canvas_capture_kind() {
        let temp = TempDir::new().expect("temp dir");
        let notebook_path = temp.path().join("nb.ipynb");
        let state = jute::state::State::new();
        state.get_notebook().load(
            &notebook_path,
            notebook(vec![source_cell(
                "capture",
                DagSource {
                    kind: "frontend".to_owned(),
                    port: "capture".to_owned(),
                    class: None,
                    schema: None,
                },
            )]),
        );
        let (engine, mut source_rx, sequencer) = source_engine_with_events_for_test();
        let mut events_rx = engine
            .subscribe_port_events()
            .expect("port event subscription");

        let error = push_capture_port_for_state(
            &state,
            Some(engine.clone()),
            "capture".to_owned(),
            base64::engine::general_purpose::STANDARD.encode(b"webm bytes"),
            1.5,
        )
        .await
        .expect_err("non canvas-capture kind is rejected");

        assert!(error
            .to_string()
            .contains("source kind must be canvas-capture"));
        assert!(source_rx.try_recv().is_err());
        let event = tokio::time::timeout(Duration::from_secs(1), events_rx.recv())
            .await
            .expect("intent rejection event")
            .expect("event broadcast");
        assert_eq!(
            event.kind(),
            &PortEventKind::IntentRejected {
                origin: Origin::Capture {
                    cell_id: "capture".to_owned(),
                },
                code: "invalid_source_kind".to_owned(),
                port: "capture".to_owned(),
            }
        );
        drop(engine);
        sequencer.shutdown().await;
    }

    #[tokio::test]
    async fn anywidget_model_state_intent_returns_comm_msg_without_source_push() {
        let state = jute::state::State::new();
        let (_engine, mut source_rx) = source_engine_for_test();

        let response = handle_anywidget_command_intent(
            &state,
            None,
            AnyWidgetCommandIntent {
                id: "cmd-2".to_owned(),
                kind: "anywidget-command".to_owned(),
                name: "model-state.update".to_owned(),
                comm_id: Some("comm-2".to_owned()),
                msg: json!({ "state": { "status": "Idle", "lastError": "" } }),
                buffers: Vec::new(),
            },
        )
        .await;

        assert_eq!(response.kind, "anywidget-command-response");
        assert_eq!(response.id, "cmd-2");
        assert_eq!(response.response["method"], "update");
        assert_eq!(response.response["state"]["status"], "Idle");
        assert_eq!(response.response["kernelDelivery"]["status"], "skipped");
        assert_eq!(
            response.response["kernelDelivery"]["reason"],
            "comm_not_open"
        );
        assert!(source_rx.try_recv().is_err());
    }

    #[derive(Default)]
    struct RecordingCommGateway {
        slot_id: Mutex<Option<String>>,
        error: Mutex<Option<String>>,
        sent: Mutex<Vec<RecordedCommSend>>,
    }

    #[derive(Debug, PartialEq, Eq)]
    struct RecordedCommSend {
        slot_id: String,
        comm_id: String,
        data: Value,
        buffers: Vec<Vec<u8>>,
    }

    #[async_trait::async_trait]
    impl ModelStateCommGateway for RecordingCommGateway {
        fn slot_for_comm(&self, _state: &jute::state::State, _comm_id: &str) -> Option<String> {
            self.slot_id.lock().expect("slot id").clone()
        }

        async fn send_comm_msg(
            &self,
            _state: &jute::state::State,
            slot_id: &str,
            comm_id: &str,
            data: Value,
            buffers: Vec<Vec<u8>>,
        ) -> Result<(), String> {
            self.sent
                .lock()
                .expect("sent comms")
                .push(RecordedCommSend {
                    slot_id: slot_id.to_owned(),
                    comm_id: comm_id.to_owned(),
                    data,
                    buffers,
                });
            match self.error.lock().expect("error").clone() {
                Some(error) => Err(error),
                None => Ok(()),
            }
        }
    }

    #[tokio::test]
    async fn model_state_update_sends_comm_msg_for_known_comm_slot_and_still_echoes() {
        let state = jute::state::State::new();
        let gateway = RecordingCommGateway {
            slot_id: Mutex::new(Some("slot-python".to_owned())),
            error: Mutex::new(None),
            sent: Mutex::new(Vec::new()),
        };
        let intent = AnyWidgetCommandIntent {
            id: "cmd-known".to_owned(),
            kind: "anywidget-command".to_owned(),
            name: "model-state.update".to_owned(),
            comm_id: Some("comm-known".to_owned()),
            msg: json!({ "state": { "status": "Running" } }),
            buffers: vec![vec![1, 2, 3]],
        };

        let response = handle_model_state_update_intent_with_gateway(&state, &intent, &gateway)
            .await
            .expect("model-state.update response");

        assert_eq!(response["method"], "update");
        assert_eq!(response["state"]["status"], "Running");
        assert_eq!(response["kernelDelivery"]["status"], "sent");
        assert_eq!(response["kernelDelivery"]["commId"], "comm-known");
        assert_eq!(response["kernelDelivery"]["slotId"], "slot-python");
        assert_eq!(
            *gateway.sent.lock().expect("sent comms"),
            vec![RecordedCommSend {
                slot_id: "slot-python".to_owned(),
                comm_id: "comm-known".to_owned(),
                data: json!({
                    "method": "update",
                    "state": { "status": "Running" },
                }),
                buffers: vec![vec![1, 2, 3]],
            }]
        );
    }

    #[tokio::test]
    async fn anywidget_model_state_custom_intent_sends_custom_comm_msg_for_known_comm_slot() {
        let state = jute::state::State::new();
        let gateway = RecordingCommGateway {
            slot_id: Mutex::new(Some("slot-python".to_owned())),
            error: Mutex::new(None),
            sent: Mutex::new(Vec::new()),
        };

        let response = handle_anywidget_command_intent_with_gateway(
            &state,
            None,
            AnyWidgetCommandIntent {
                id: "cmd-custom".to_owned(),
                kind: "anywidget-command".to_owned(),
                name: "model-state.custom".to_owned(),
                comm_id: Some("comm-custom".to_owned()),
                msg: json!({ "content": { "event": "clicked", "count": 2 } }),
                buffers: vec![vec![9, 8, 7]],
            },
            &gateway,
        )
        .await;

        assert_eq!(response.kind, "anywidget-command-response");
        assert_eq!(response.id, "cmd-custom");
        assert_eq!(response.response["method"], "custom");
        assert_eq!(response.response["content"]["event"], "clicked");
        assert_eq!(response.response["kernelDelivery"]["status"], "sent");
        assert_eq!(response.response["kernelDelivery"]["commId"], "comm-custom");
        assert_eq!(response.response["kernelDelivery"]["slotId"], "slot-python");
        assert_eq!(
            *gateway.sent.lock().expect("sent comms"),
            vec![RecordedCommSend {
                slot_id: "slot-python".to_owned(),
                comm_id: "comm-custom".to_owned(),
                data: json!({
                    "method": "custom",
                    "content": { "event": "clicked", "count": 2 },
                }),
                buffers: vec![vec![9, 8, 7]],
            }]
        );
    }

    #[tokio::test]
    async fn model_state_update_reports_failed_comm_send_without_rejecting_echo() {
        let state = jute::state::State::new();
        let gateway = RecordingCommGateway {
            slot_id: Mutex::new(Some("slot-python".to_owned())),
            error: Mutex::new(Some("kernel disconnected".to_owned())),
            sent: Mutex::new(Vec::new()),
        };
        let intent = AnyWidgetCommandIntent {
            id: "cmd-fail".to_owned(),
            kind: "anywidget-command".to_owned(),
            name: "model-state.update".to_owned(),
            comm_id: Some("comm-fail".to_owned()),
            msg: json!({ "state": { "status": "Busy" } }),
            buffers: Vec::new(),
        };

        let response = handle_model_state_update_intent_with_gateway(&state, &intent, &gateway)
            .await
            .expect("model-state.update response");

        assert_eq!(response["method"], "update");
        assert_eq!(response["state"]["status"], "Busy");
        assert_eq!(response["kernelDelivery"]["status"], "failed");
        assert_eq!(response["kernelDelivery"]["commId"], "comm-fail");
        assert_eq!(response["kernelDelivery"]["slotId"], "slot-python");
        assert_eq!(response["kernelDelivery"]["error"], "kernel disconnected");
        assert_eq!(gateway.sent.lock().expect("sent comms").len(), 1);
    }

    #[tokio::test]
    async fn model_state_update_degrades_gracefully_for_unknown_comm_slot() {
        let state = jute::state::State::new();
        let gateway = RecordingCommGateway::default();
        let intent = AnyWidgetCommandIntent {
            id: "cmd-unknown".to_owned(),
            kind: "anywidget-command".to_owned(),
            name: "model-state.update".to_owned(),
            comm_id: Some("comm-missing".to_owned()),
            msg: json!({ "state": { "status": "Idle" } }),
            buffers: Vec::new(),
        };

        let response = handle_model_state_update_intent_with_gateway(&state, &intent, &gateway)
            .await
            .expect("model-state.update response");

        assert_eq!(response["method"], "update");
        assert_eq!(response["state"]["status"], "Idle");
        assert_eq!(response["kernelDelivery"]["status"], "skipped");
        assert_eq!(response["kernelDelivery"]["commId"], "comm-missing");
        assert_eq!(response["kernelDelivery"]["reason"], "comm_not_open");
        assert!(gateway.sent.lock().expect("sent comms").is_empty());
    }

    #[tokio::test]
    async fn anywidget_rejects_non_allowlisted_intent_without_source_push() {
        let state = jute::state::State::new();
        let (engine, mut source_rx) = source_engine_for_test();

        let response = handle_anywidget_command_intent(
            &state,
            Some(engine),
            AnyWidgetCommandIntent {
                id: "cmd-3".to_owned(),
                kind: "anywidget-command".to_owned(),
                name: "shell.run".to_owned(),
                comm_id: None,
                msg: json!({ "command": "gcloud", "args": ["projects", "list"] }),
                buffers: Vec::new(),
            },
        )
        .await;

        assert_eq!(response.kind, "anywidget-command-response");
        assert_eq!(response.id, "cmd-3");
        assert_eq!(response.response["error"]["code"], "intent_not_allowlisted");
        assert!(source_rx.try_recv().is_err());
    }
}
