-- Analytics report query index.
-- Source-of-truth SQL lives in the adjacent per-query files loaded via include_str! in engine.rs.
--
-- daily_report.sql
-- weekly_report.sql
-- monthly_report.sql
-- model_breakdown.sql
-- project_breakdown.sql
-- session_detail.sql
-- live_session_snapshot.sql
