[package]
name = "spur-rest-table-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["duckdb-bundled"]
duckdb-bundled = ["duckdb/bundled"]

[dependencies]
anyhow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
async-trait.workspace = true
duckdb = { workspace = true, features = ["vtab"] }
futures.workspace = true
reqwest = { workspace = true }
serde = { workspace = true }
serde_json.workspace = true
serde_yaml = "0.9"
thiserror.workspace = true
tokio = { workspace = true }
toml = { version = "0.8", features = ["preserve_order"] }
tracing.workspace = true
indexmap = { version = "2", features = ["serde"] }

[dev-dependencies]
wiremock = "0.6"
tokio = { workspace = true }
