// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JuteDeckCellMetadata } from "./JuteDeckCellMetadata";
import type { SpurCellMetadata } from "./SpurCellMetadata";

/**
 * Metadata for a cell.
 */
export type CellMetadata = {
  [key: string]: unknown;
  /**
   * SPUR-managed cell metadata.
   */
  spur?: SpurCellMetadata;
  /**
   * jute-deck per-cell metadata (layout, hidden, speaker_notes, ...).
   */
  jute_deck?: JuteDeckCellMetadata;
};
