// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cell kind to create when inserting a notebook cell.
 */
export type CellKind = "raw" | "markdown" | "code";
