// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DagSource } from "./DagSource";
import type { PortSpec } from "./PortSpec";

/**
 * Reactive DAG metadata persisted under `cell.metadata.spur.dag`.
 */
export type CellDagMetadata = {
  /**
   * Ports this cell produces.
   */
  produces: Array<PortSpec>;
  /**
   * Ports this cell consumes.
   */
  consumes: Array<string>;
  /**
   * Source port that feeds this cell.
   */
  source?: DagSource;
};
