// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpurCellMetadata } from "./SpurCellMetadata";

/**
 * Metadata for a cell.
 */
export type CellMetadata = {
  /**
   * SPUR-managed cell metadata.
   */
  spur?: SpurCellMetadata;
};
