// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunTarget } from "./RunTarget";

/**
 * Persisted per-cell cron trigger config (`cell.metadata.spur.cron`).
 *
 * Run history/last-run/next-fire are not stored here; they live in the
 * in-memory scheduler.
 */
export type CellCronTrigger = {
  /**
   * Whether the schedule is currently armed.
   */
  enabled: boolean;
  /**
   * 5-field `Unix` cron expression, such as every 15 minutes.
   */
  cron: string;
  /**
   * `IANA` timezone name, for example `America/Los_Angeles`.
   */
  timezone: string;
  /**
   * Cell-only vs cascade. Defaults to cascade.
   */
  run_target: RunTarget;
  /**
   * Skip a fire if the previous run is still going. Defaults true.
   */
  skip_if_running: boolean;
  /**
   * Back-fill a window that elapsed while `SPUR` was closed. Defaults false.
   */
  catch_up: boolean;
};
