// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-cell code language label persisted under `cell.metadata.spur.code_type`.
 */
export type CodeType = "python" | "javascript" | "rust" | "go";
