// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Column metadata captured for a notebook datasource.
 */
export type Column = {
  /**
   * Column name.
   */
  name: string;
  /**
   * SQL type reported by the datasource engine.
   */
  sqlType: string;
};
