// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Open a comm to the frontend, used for interactive widgets.
 */
export type CommOpen = {
  /**
   * The unique ID of the comm.
   */
  comm_id: string;
  /**
   * The target name of the comm. If this is is not understood by the
   * frontend, they must reply with a `comm_close` message.
   */
  target_name: string;
  /**
   * The data to be sent to the frontend.
   */
  data: JsonValue;
};
