// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A one-way comm message, with no expected reply format. This struct is reused
 * for both `comm_msg` and `comm_close` message types.
 */
export type CommMessage = {
  /**
   * The unique ID of the comm.
   */
  comm_id: string;
  /**
   * The data to be sent to the frontend.
   */
  data: JsonValue;
  /**
   * Binary buffers attached to the kernel message envelope.
   */
  buffers: Array<Array<number>>;
};
