// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse compile/run phase for compiled notebook cells.
 */
export type CompilePhase = "compiling" | "running";
