// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Table } from "./Table";

/**
 * Saved API connection template metadata. Secret values are never included.
 */
export type ConnectionTemplate = {
  /**
   * Saved connection name.
   */
  name: string;
  /**
   * Provider key when the connection came from the provider catalog.
   */
  provider: string | null;
  /**
   * Optional UI grouping key.
   */
  group: string | null;
  /**
   * Table manifest TOML used to reconstruct the connection.
   */
  manifestToml: string;
  /**
   * Tables exposed by this connection.
   */
  tables: Array<Table>;
  /**
   * Environment variable keys required by this connection.
   */
  credentialEnvVars: Array<string>;
  /**
   * Global credential profile selected for this connection.
   */
  credentialRef: string | null;
  /**
   * Template creation timestamp.
   */
  createdAt: string;
  /**
   * Template update timestamp.
   */
  updatedAt: string;
};
