// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Table } from "./Table";

export type ConnectionTemplate = {
  name: string;
  provider: string | null;
  group: string | null;
  manifestToml: string;
  tables: Array<Table>;
  credentialEnvVars: Array<string>;
  createdAt: string;
  updatedAt: string;
};
