// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Saved credential profile metadata. Secret values are never included.
 */
export type CredentialProfileSummary = {
  /**
   * Stable profile identifier used by saved API connections.
   */
  id: string;
  /**
   * Provider key this profile can satisfy.
   */
  provider: string;
  /**
   * Human-readable profile label.
   */
  label: string;
  /**
   * Credential keys present in the profile.
   */
  keys: Array<string>;
  /**
   * Profile creation timestamp.
   */
  createdAt: string;
  /**
   * Profile update timestamp.
   */
  updatedAt: string;
};
