// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonControlError } from "./DaemonControlError";
import type { DaemonControlResult } from "./DaemonControlResult";
import type { DaemonRecentEntry } from "./DaemonRecentEntry";

/**
 * A daemon control protocol response.
 */
export type DaemonControlResponse = {
  ok: boolean;
  path?: string;
  entries?: Array<DaemonRecentEntry>;
  result?: DaemonControlResult;
  error?: DaemonControlError;
};
