// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error payload returned by daemon control failures.
 */
export type DaemonControlError = {
  /**
   * Stable machine-readable error code.
   */
  code: string;
  /**
   * Human-readable error message.
   */
  message: string;
};
