// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonCell } from "./DaemonCell";
import type { DaemonNotebookSnapshot } from "./DaemonNotebookSnapshot";
import type { DatasourceEntry } from "./DatasourceEntry";
import type { NotebookDelta } from "./NotebookDelta";

/**
 * Successful daemon control payloads.
 */
export type DaemonControlResult =
  | { type: "empty"; data: Record<string, never> }
  | { type: "delta"; data: NotebookDelta }
  | { type: "cell"; data: DaemonCell }
  | { type: "snapshot"; data: DaemonNotebookSnapshot }
  | { type: "datasource"; data: DatasourceEntry }
  | { type: "datasources"; data: Array<DatasourceEntry> };
