// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellKind } from "./CellKind";
import type { CodeType } from "./CodeType";
import type { NotebookRoot } from "./NotebookRoot";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Operation encoded in a daemon control request.
 */
export type DaemonControlCommand =
  | { command: "open"; path: string }
  | { command: "rename"; from: string; to: string }
  | { command: "new" }
  | { command: "new_at"; path: string }
  | { command: "reopen" }
  | { command: "close" }
  | {
      command: "attach_datasource";
      name: string;
      path: string;
      group: string | null;
    }
  | { command: "add_api_datasource"; name: string; source: string }
  | { command: "list_nango_providers" }
  | { command: "preview_open_api_tables"; spec_text: string }
  | {
      command: "add_api_datasource_from_import";
      name: string;
      provider: string | null;
      spec_text: string | null;
      credentials: [string, string][];
    }
  | {
      command: "add_api_datasource_from_manifest";
      name: string;
      manifest_toml: string;
      credentials: [string, string][];
    }
  | {
      command: "save_api_connection_template";
      name: string;
      provider?: string;
      manifest_toml: string;
    }
  | { command: "oauth_connect"; name: string }
  | { command: "detach_datasource"; name: string }
  | { command: "list_datasources" }
  | { command: "list_saved_connections" }
  | {
      command: "attach_saved_connection";
      name: string;
      credentials: [string, string][];
    }
  | { command: "delete_saved_connection"; name: string }
  | {
      command: "update_saved_connection";
      name: string;
      spec_text: string | null;
      credentials: [string, string][];
    }
  | { command: "list_recents" }
  | { command: "remove_from_recents"; path: string }
  | { command: "set_pinned"; path: string; pinned: boolean }
  | {
      command: "write_cell";
      id: string;
      source: string;
      expected_version: number | null;
      last_edited_by: string | null;
    }
  | { command: "read_cell"; id: string }
  | {
      command: "insert_cell";
      kind: CellKind;
      after_id: string | null;
      source: string;
      last_edited_by: string | null;
      code_type?: CodeType;
    }
  | { command: "load"; path: string }
  | { command: "replace_notebook"; path: string; contents: NotebookRoot }
  | { command: "delete_cell"; id: string; expected_version: number }
  | {
      command: "set_cell_metadata";
      id: string;
      patch: JsonValue;
      expected_version: number;
    }
  | { command: "snapshot" }
  | { command: "apply_edit"; id: string; source: string }
  | { command: "flush_notebook" };
