// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellKind } from "./CellKind";

/**
 * Operation encoded in a daemon control request.
 */
export type DaemonControlCommand =
  | { command: "open"; path: string }
  | { command: "new" }
  | { command: "reopen" }
  | { command: "close" }
  | { command: "list_recents" }
  | { command: "remove_from_recents"; path: string }
  | { command: "set_pinned"; path: string; pinned: boolean }
  | { command: "shutdown" }
  | {
      command: "write_cell";
      id: string;
      source: string;
      expected_version: number | null;
      last_edited_by: string | null;
    }
  | { command: "read_cell"; id: string }
  | {
      command: "insert_cell";
      kind: CellKind;
      after_id: string | null;
      source: string;
    }
  | { command: "delete_cell"; id: string; expected_version: number }
  | { command: "snapshot" }
  | { command: "apply_edit"; id: string; source: string }
  | { command: "flush_notebook" };
