// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Cell payload returned by daemon control read operations.
 */
export type DaemonCell = {
  id: string;
  kind: string;
  version: number;
  lastEditedBy: string | null;
  source: string;
  execCount: number | null;
  status: string;
  outputs: Array<JsonValue>;
};
