// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellDagMetadata } from "./CellDagMetadata";
import type { JuteDeckCellMetadata } from "./JuteDeckCellMetadata";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Self-contained cell payload carried by deltas and daemon control reads.
 */
export type DaemonCell = {
  id: string;
  kind: string;
  version: number;
  lastEditedBy: string | null;
  datasourceSetup?: boolean;
  dagMetadata?: CellDagMetadata;
  juteDeckMetadata?: JuteDeckCellMetadata;
  metadataOther?: Record<string, JsonValue>;
  source: string;
  execCount: number | null;
  status: string;
  outputs: Array<JsonValue>;
};
