// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotebookRoot } from "./NotebookRoot";

/**
 * Full notebook snapshot returned by daemon control.
 */
export type DaemonNotebookSnapshot = { root: NotebookRoot; version: number };
