// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source descriptor for a consumed DAG port.
 */
export type DagSource = {
  /**
   * Source kind.
   */
  kind: string;
  /**
   * Source port identifier.
   */
  port: string;
  /**
   * Source class. Omitted legacy metadata defaults to dataframe at runtime.
   */
  class?: string;
  /**
   * Optional declared Arrow schema JSON, in the manifest schema dialect.
   */
  schema?: unknown;
};
