// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local datasource file type supported by the notebook daemon.
 */
export type DatasourceKind =
  | "csv"
  | "parquet"
  | "json"
  | "duck_db"
  | "sqlite"
  | "api_tables";
