// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { DatasourceKind } from "./DatasourceKind";
import type { Table } from "./Table";

/**
 * Catalog entry describing one datasource attached to a notebook.
 */
export type DatasourceEntry = {
  /**
   * User-facing datasource name.
   */
  name: string;
  /**
   * Datasource file path.
   */
  path: string;
  /**
   * Datasource file kind.
   */
  kind: DatasourceKind;
  /**
   * Optional UI grouping key.
   */
  group: string | null;
  /**
   * Columns discovered for the datasource.
   */
  columns: Array<Column>;
  /**
   * Row count when known.
   */
  rowCount: number | null;
  /**
   * Tables discovered for multi-table datasources.
   */
  tables: Array<Table>;
};
