// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellKind } from "./CellKind";
import type { RunCellEvent } from "./RunCellEvent";

/**
 * Kind of store mutation represented by a [`NotebookDelta`].
 */
export type DeltaKind =
  | {
      type: "cellWritten";
      /**
       * Cell identifier.
       */
      id: string;
    }
  | {
      type: "cellInserted";
      /**
       * New cell identifier.
       */
      id: string;
      /**
       * Kind of inserted cell.
       */
      kind: CellKind;
      /**
       * Existing cell identifier the new cell was inserted after.
       */
      after_id: string | null;
    }
  | {
      type: "cellDeleted";
      /**
       * Cell identifier.
       */
      id: string;
    }
  | {
      type: "runCellEvent";
      /**
       * Cell identifier.
       */
      cell_id: string;
      /**
       * Applied run event.
       */
      event: RunCellEvent;
    }
  | { type: "loaded" };
