// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonCell } from "./DaemonCell";
import type { NotebookRoot } from "./NotebookRoot";
import type { RunCellEvent } from "./RunCellEvent";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Kind of store mutation represented by a [`NotebookDelta`].
 */
export type DeltaKind =
  | {
      type: "cellWritten";
      /**
       * Post-mutation cell, self-contained so the reducer needs no refetch.
       */
      cell: DaemonCell;
    }
  | {
      type: "cellInserted";
      /**
       * Post-mutation inserted cell, self-contained so the reducer needs no refetch.
       */
      cell: DaemonCell;
      /**
       * Existing cell identifier the new cell was inserted after.
       */
      after_id: string | null;
    }
  | {
      type: "cellDeleted";
      /**
       * Cell identifier.
       */
      id: string;
    }
  | {
      type: "runCellEvent";
      /**
       * Cell identifier.
       */
      cell_id: string;
      /**
       * Applied run event.
       */
      event: RunCellEvent;
    }
  | {
      type: "dagStatusChanged";
      /**
       * Full DAG status snapshot for frontend reducers.
       */
      snapshot: JsonValue;
    }
  | {
      type: "loaded";
      /**
       * Full notebook root after the load, self-contained for the reducer.
       */
      root: NotebookRoot;
    };
