// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App-mode frontend declaration persisted under `cell.metadata.spur.frontend`.
 *
 * Advisory props are intentionally not persisted; App mode keeps the durable
 * declaration to `kind`, `binds`, and `emits`.
 */
export type FrontendCellMetadata = {
  /**
   * Frontend renderer kind, such as `html`.
   */
  kind?: string;
  /**
   * DAG ports this frontend cell reads.
   */
  binds: Array<string>;
  /**
   * DAG ports this frontend cell emits.
   */
  emits: Array<string>;
};
