// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit slide-layout values.
 */
export type JuteDeckLayout =
  | "auto"
  | "title"
  | "section"
  | "content"
  | "bullets"
  | "code"
  | "output"
  | "code-output"
  | "two-col"
  | "image"
  | "blank";
