// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JuteDeckLayout } from "./JuteDeckLayout";

/**
 * jute-deck per-cell metadata.
 */
export type JuteDeckCellMetadata = {
  /**
   * Explicit slide layout; omitted = inferred from cell content.
   */
  layout?: JuteDeckLayout;
  /**
   * Skip this cell in deck/present mode while keeping it in the notebook.
   */
  hidden?: boolean;
  /**
   * Markdown speaker notes shown only via the S key overlay.
   */
  speaker_notes?: string;
  /**
   * Per-slide theme override (theme id from the notebook-level theme list).
   */
  theme_override?: string;
  /**
   * Bullet-by-bullet reveal in present mode (markdown bullets only).
   */
  fragments?: boolean;
  /**
   * Per-slide background color or image URL.
   */
  background?: string;
};
