// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * jute-deck notebook-level metadata.
 */
export type JuteDeckNotebookMetadata = {
  /**
   * Theme id; defaults to "minimal-light".
   */
  theme?: string;
  /**
   * Slide aspect ratio; defaults to "16:9".
   */
  aspect?: string;
  /**
   * Deck title override (defaults to filename).
   */
  title?: string;
  /**
   * Deck author display name.
   */
  author?: string;
};
