// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaKind } from "./DeltaKind";

/**
 * Broadcast notification emitted after each store mutation.
 */
export type NotebookDelta = {
  /**
   * Monotonic document version after the mutation.
   */
  version: number;
  /**
   * Kind of mutation represented by this delta.
   */
  kind: DeltaKind;
};
