// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaKind } from "./DeltaKind";

/**
 * Broadcast notification emitted after each store mutation.
 */
export type NotebookDelta = {
  /**
   * Monotonic document version after the mutation.
   */
  version: number;
  /**
   * Worktree path of the notebook this delta belongs to. `None` only when the
   * store has no loaded path yet (a fresh/unsaved store). Used by the frontend
   * to drop deltas that belong to a different open notebook window.
   */
  path?: string;
  /**
   * Kind of mutation represented by this delta.
   */
  kind: DeltaKind;
};
