// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TablePreview } from "./TablePreview";

/**
 * Preview payload for OpenAPI-generated API tables.
 */
export type OpenApiTablePreview = {
  /**
   * Tables detected from the OpenAPI document.
   */
  tables: Array<TablePreview>;
};
