// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Produced DAG port descriptor.
 */
export type PortSpec = {
  /**
   * Port identifier.
   */
  port: string;
  /**
   * Representation type for this port.
   */
  repr: string;
  /**
   * Optional display label.
   */
  display?: string;
};
