// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TablePreview } from "./TablePreview";

/**
 * Nango provider metadata summarized for API datasource onboarding.
 */
export type ProviderSummary = {
  /**
   * Provider key from the vendored Nango providers snapshot.
   */
  name: string;
  /**
   * Underlying Nango provider key used when importing a selected catalog row.
   */
  providerKey: string;
  /**
   * Human-readable provider name.
   */
  displayName: string;
  /**
   * Primary provider category.
   */
  category: string;
  /**
   * Import tier derived from the provider auth mode.
   */
  tier: string;
  /**
   * Nango auth mode string.
   */
  authMode: string;
  /**
   * Support level for the bundled catalog entry.
   */
  supportLevel: string;
  /**
   * Provider-level fulfillment status for API-as-table readiness.
   */
  fulfillmentStatus: string;
  /**
   * Machine-readable reason when fulfillment is blocked.
   */
  blockedReason?: string;
  /**
   * API spec source key when this row came from an experimental spec crosswalk.
   */
  specSourceKey: string | null;
  /**
   * API spec URL when this row came from an experimental spec crosswalk.
   */
  specUrl: string | null;
  /**
   * Number of experimental API spec candidates attached to this provider.
   */
  experimentalSpecCount: number;
  /**
   * Runtime base URL from a supported manifest when known.
   */
  baseUrl: string | null;
  /**
   * Environment variables required by the supported manifest.
   */
  credentialEnvVars: Array<string>;
  /**
   * Table previews available from a supported bundled manifest.
   */
  tables: Array<TablePreview>;
  /**
   * Action previews available from a supported bundled manifest.
   */
  actions: Array<TablePreview>;
};
