// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nango provider metadata summarized for API datasource onboarding.
 */
export type ProviderSummary = {
  /**
   * Provider key from the vendored Nango providers snapshot.
   */
  name: string;
  /**
   * Human-readable provider name.
   */
  displayName: string;
  /**
   * Primary provider category.
   */
  category: string;
  /**
   * Import tier derived from the provider auth mode.
   */
  tier: string;
  /**
   * Nango auth mode string.
   */
  authMode: string;
};
