// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recent notebook entry enriched for the Tauri webview.
 */
export type RecentNotebookEntry = {
  /**
   * Absolute notebook path.
   */
  path: string;
  /**
   * Last opened time in RFC3339 format.
   */
  lastOpened: string;
  /**
   * Whether the notebook lives under the scratch directory.
   */
  isScratch: boolean;
  /**
   * Whether the notebook is pinned in recents.
   */
  pinned: boolean;
  /**
   * Whether the path-derived kernel slot has a live kernel.
   */
  kernelAlive: boolean;
  /**
   * Whether this entry is the daemon's current notebook.
   */
  isCurrent: boolean;
};
