// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecentNotebookEntry } from "./RecentNotebookEntry";

/**
 * Payload emitted when the recent-notebooks list changes.
 */
export type RecentsChangedEvent = {
  /**
   * Current recent-notebook entries.
   */
  entries: Array<RecentNotebookEntry>;
};
