// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RSSHub subscription table requested by the datasource wizard.
 */
export type RssSubscriptionRequest = {
  /**
   * Zero-argument table to expose for this feed.
   */
  table: string;
  /**
   * RSS/Atom URL or RSSHub route URL fetched by the table.
   */
  url: string;
};
