// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClearOutput } from "./ClearOutput";
import type { CommMessage } from "./CommMessage";
import type { CommOpen } from "./CommOpen";
import type { CompilePhase } from "./CompilePhase";
import type { DisplayData } from "./DisplayData";
import type { ErrorReply } from "./ErrorReply";
import type { ExecuteResult } from "./ExecuteResult";

/**
 * Events that can be received while running a cell.
 */
export type RunCellEvent =
  | { event: "started" }
  | {
      event: "compile_progress";
      data: {
        /**
         * Current compile/run phase.
         */
        phase: CompilePhase;
        /**
         * Current compile target, when known.
         */
        current: string | null;
      };
    }
  | { event: "stdout"; data: string }
  | { event: "stderr"; data: string }
  | { event: "execute_result"; data: ExecuteResult }
  | { event: "display_data"; data: DisplayData }
  | { event: "update_display_data"; data: DisplayData }
  | { event: "clear_output"; data: ClearOutput }
  | { event: "comm_open"; data: CommOpen }
  | { event: "comm_msg"; data: CommMessage }
  | { event: "comm_close"; data: CommMessage }
  | { event: "error"; data: ErrorReply }
  | { event: "disconnect"; data: string }
  | {
      event: "finished";
      data: {
        /**
         * Kernel execution count when available.
         */
        exec_count: number | null;
        /**
         * Terminal execution status.
         */
        status: string;
      };
    };
