// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellDagMetadata } from "./CellDagMetadata";

/**
 * SPUR-managed metadata persisted under `cell.metadata.spur`.
 */
export type SpurCellMetadata = {
  /**
   * Per-cell monotonic content version.
   */
  version: number;
  /**
   * Agent that last edited the cell through notebook MCP tools.
   */
  last_edited_by?: string;
  /**
   * Marks the SPUR-managed datasource setup cell.
   */
  datasource_setup?: boolean;
  /**
   * Reactive DAG wiring metadata for this cell.
   */
  dag?: CellDagMetadata;
};
