// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SPUR-managed metadata persisted under `cell.metadata.spur`.
 */
export type SpurCellMetadata = {
  /**
   * Per-cell monotonic content version.
   */
  version: number;
};
