// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";

/**
 * Table metadata captured for a multi-table notebook datasource.
 */
export type Table = {
  /**
   * Table name.
   */
  name: string;
  /**
   * Columns discovered for the table.
   */
  columns: Array<Column>;
  /**
   * Row count when known.
   */
  rowCount: number | null;
};
