// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Column metadata returned when previewing OpenAPI-generated API tables.
 */
export type TablePreviewColumn = {
  /**
   * Column name.
   */
  name: string;
  /**
   * Gateway column type.
   */
  ty: string;
  /**
   * JSONPath used to extract the column value.
   */
  json: string;
};
