// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TablePreviewColumn } from "./TablePreviewColumn";

/**
 * Table metadata returned when previewing OpenAPI-generated API tables.
 */
export type TablePreview = {
  /**
   * Generated table name.
   */
  name: string;
  /**
   * Request path for the table.
   */
  path: string;
  /**
   * JSONPath to the response array when detected.
   */
  responsePath: string | null;
  /**
   * Generated columns.
   */
  columns: Array<TablePreviewColumn>;
};
